apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: 192.168.1.170:5000/eureka-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8761